# Generated by Django 3.1.7 on 2021-03-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='Dni',
            new_name='dni',
        ),
    ]
