export enum ActionsType {
    ADD_BAR = "addBar",
    BAR_DELETE = "deleteBar",
    BAR_RESET_STATE = "resetBarState",
    CHECK_AUTH = "checkAuth",
    FAVORITE_ADD = "addFavorite",
    FAVORITE_REMOVE = "removeFavorite",
    FETCH_BAR = "fetchBar",
    FETCH_BARS = "fetchBars",
    FETCH_PAGINATION = "fetchPagination",
    BOOK_ADD="bookAdd",
    BOOK_REMOVE ="bookRemove",
    LOGIN = "login",
    DESACTIVATE = "desactivate",
    ACTIVATE = "activate",
    LOGOUT = "logout",
    REGISTER = "register",
    FETCH_PROFILE = "fetchProfile",
    FETCH_PROFILE_FOLLOW = "fetchProfileFollow",
    FETCH_PROFILE_UNFOLLOW = "fetchProfileUnfollow",

}// end_ActionsTypes