# Generated by Django 3.1.7 on 2021-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='valoration',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
