# Generated by Django 3.1.7 on 2021-05-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_auto_20210505_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idPromotion', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('idBar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
