# Generated by Django 3.1.7 on 2021-05-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_promotions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='idBar',
            new_name='bar',
        ),
    ]
