# Generated by Django 3.1.7 on 2021-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_auto_20210512_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
